### ISSUE TITLE
PyQt 4 pinning

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyface-feedstock#10]
Found that there is a PyQt 4 pinning, which was [added]( https://github.com/conda-forge/pyface-feedstock/commit/1c9be1f20fc7ffa23533cf6a8834c867540427c6 ) recently. If this is needed, we might need to pull the old versions. The reason for this is the `conda` solver prioritizes the latest overall set of versions over build numbers. As a consequence it will downgrade to old unpinned packages to get the latest PyQt and Qt versions. IOW this pinning doesn't appear to be respected currently.

FWIW the old packages will still be available, but under the `broken` label.

Any thoughts or questions about this?

**Comment by jakirkham** [comment]
cc @francisco-dlp

**Comment by grlee77** [comment]
I am pretty sure the version here requires PyQt4, but current master does
work with 5 too.  I believe the same is also true for traitsui


On Jun 19, 2017 6:55 AM, "jakirkham" <notifications@github.com> wrote:

cc @francisco-dlp <https://github.com/francisco-dlp>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/pyface-feedstock/issues/10#issuecomment-309308392>,
or mute the thread

**Comment by grlee77** [comment]
- For `pyface` only those uploaded in Feb of this year will have the 4.11.* pyqt pinning:
https://anaconda.org/conda-forge/pyface/files
All of the older ones (~24 of them) should be pulled.  

- For `traitsui`, `pyqt` is not currently listed as a runtime requirement, but gets pulled in indirectly via the `pyface` runtime requirement.  Do we need to added the pyqt version explicitly to `meta.yaml` there as well or will that be okay to leave it as is once the offending pyface packages have been removed?

- For `mayavi` both a `traitsui` dependency and a `pyqt` dependency are listed.  I had added a pin to pyqt <5 in conda-forge/mayavi-feedstock#13, although there is currently a mysterious build failure on CircleCI so that pinning has not yet been merged.  Is it best to explicitly pin to 4.11.* or is it better to remove `pyqt` from the runtime as it will get pulled in indirectly via traitsui->pyface->pyqt?

**Comment by grlee77** [comment]
ping @jakirkham:  see previous comment on packages missing the pinning that should be pulled

**Comment by jakirkham** [comment]
Sorry about not getting back to this sooner. Have pulled all of the old `pyface` packages. I think that should resolve the issue hopefully. Please let me know if I missed any.

As for the other packages, if they use `pyqt` directly, they probably should list the dependency and pin it. If not, then I think pulling the bad `pyface` packages will have fixed the issue.

**Comment by jakirkham** [comment]
Is this ok to close?

**Comment by grlee77** [comment]
Yes.  Thanks for removing the old packages.  As of #11, it should now work with Qt5 too.
